apiVersion: v1
kind: Service
metadata:
  name: {{ include "sacloud-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "sacloud-webhook.name" . }}
    chart: {{ include "sacloud-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "sacloud-webhook.name" . }}
    release: {{ .Release.Name }}
