name: Build Image from tag

on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-cert-manager-v')
    defaults:
      run:
        shell: bash

    steps:
      - name: Get tagname
        run: echo "::set-env name=TAG_NAME::${TAG_REF##refs/tags/}"
        env:
          TAG_REF: ${{ github.ref }}
      - name: Get version
        run: echo "::set-env name=VERSION::${TAG_NAME%%-cert-manager-v*}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx
        run: |
          make push PLATFORM=linux/amd64,linux/arm64 IMAGE_TAG=${VERSION}
